# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: NeSy-GeMs @ ICLR 2023
email: nesygems2023@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  We are organizing a very exciting workshop on the intersection of Neurosymbolic and Generative Modeling. The workshop is scheduled to take place jointly with ICLR 2023 in Kigali, Rwanda, from the 1st to the 5th of May. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: NeSy_GeMs
github_username:  nesygems

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
- index.md
- callforpapers.md
- speakers.md
# - organizers.md
# - contact.md
#- schedule.md
#- papers.md

# Define collections (speakers, organizers, papers)
# To turn off any of these collections, just set "output" to "false"
collections:
  speakers:
    output: false
  organizers:
    output: true
  schedule:
    sort_by: sequence_id
    output: false
  papers:
    sort_by: sequence_id
    output: false


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# A two-line attribution (remove this if you have to, but we'd appreciate if you leave this as is)
attribution: >
  Based on a <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> template from a <a href="https://krrish94.github.io">lazy grad student</a>.